POST http://127.0.0.1:4000/block/create
Content-Type: application/json

{
  "startTime": "14:00",
  "finishTime": "15:00",
  "description": "BLOQUE-5"
}

######


GET http://127.0.0.1:4000/block


######