POST http://127.0.0.1:4000/professional/create
Content-Type: application/json

{
    "id_speciality": 1,
    "id_user": 1,
    "username" : "try0wasp1",
    "password" : "123456789",
    "linkToConsultation": "http://linkToCall.url"
}

######

POST http://127.0.0.1:4000/professional/login
Content-Type: application/json

{
    "username" : "try0wasp1",
    "password": "123456789"
}

######

POST http://127.0.0.1:4000/professional/logout
X-Session-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiI0IiwiaWF0IjoxNjU3MjMzOTMzLCJleHAiOjE2NTc4Mzg3MzN9.hqKHSv4C8sWJzaBZHUaHWdvAliDfkIA2ErkWV-asNWo
