POST http://127.0.0.1:4000/schedule/create
Content-Type: application/json

{
  "id_professional": 1,
  "id_block": 1,
  "currentDate": "2022-07-06"
}

######

GET http://127.0.0.1:4000/schedule/professional/2



####