POST http://127.0.0.1:4000/user/create
Content-Type: application/json

{
    "dni" : "22222222",
    "names": "JHON DOE",
    "surnames": "KNOU NUTING",
    "birthdate": "1994-07-10T04:00:00.000Z"   
}

######

POST http://127.0.0.1:4000/user/test